name: Create Anki Addon
on:
  push:
    tags:
      - "*"
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: "zip"
          filename: "freqman.ankiaddon"
          exclusions: "*.git* /*node_modules/* .editorconfig"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "freqman.ankiaddon"
          token: ${{ secrets.GITHUB_TOKEN }}
